# Generated by Django 5.2.11 on 2026-03-04

from django.db import migrations, models


def create_singleton(apps, schema_editor):
    MasterPayments = apps.get_model('payments', 'MasterPayments')
    if not MasterPayments.objects.exists():
        MasterPayments.objects.create(enabled=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MasterPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Payments',
                'verbose_name_plural': 'Master Payments',
            },
        ),
        migrations.RunPython(create_singleton, migrations.RunPython.noop),
    ]
