# Generated by Django 5.2.11 on 2026-03-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptionplan_user_last_study_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mondai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('video_type', models.CharField(choices=[('upload', 'Upload'), ('link', 'Link'), ('embed', 'Embed')], default='upload', max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='mondai_videos/')),
                ('video_url', models.URLField(blank=True)),
                ('video_embed_url', models.URLField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mondais', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mondais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MondaiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(blank=True, max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mondai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.mondai')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MondaiVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120)),
                ('reading', models.CharField(blank=True, max_length=120)),
                ('meaning', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mondai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab', to='core.mondai')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mondai',
            index=models.Index(fields=['status', 'created_at'], name='core_mondai_status_27c7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='mondai',
            index=models.Index(fields=['created_by', 'updated_at'], name='core_mondai_created_b28969_idx'),
        ),
    ]
