# Generated by Django 5.2.11 on 2026-03-01 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_xp_events_week_fix_and_daily_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameIndex(
            model_name='dailyquiztask',
            new_name='core_dailyq_user_id_819bb5_idx',
            old_name='core_dailyquiztask_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='mondaianswerattempt',
            new_name='core_mondai_user_id_6c383e_idx',
            old_name='core_mondaiattempt_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='mondaianswerattempt',
            new_name='core_mondai_mondai__42cd4b_idx',
            old_name='core_mondaiattempt_q_date_idx',
        ),
        migrations.RenameIndex(
            model_name='xpevent',
            new_name='core_xpeven_created_45ad34_idx',
            old_name='core_xpevent_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='xpevent',
            new_name='core_xpeven_user_id_1e4115_idx',
            old_name='core_xpevent_user_created_at_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'expires_at'], name='core_emailo_email_62f8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user'], name='core_emailo_user_id_292b0a_idx'),
        ),
    ]
