# Generated by Django 5.2.11 on 2026-03-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
