# Generated by Django 5.2.11 on 2026-03-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_exam'),
        ('core', '0009_level_unit_grammarcontent_vocabularyitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='administration.exam'),
        ),
        migrations.AddField(
            model_name='grammarcontent',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_items', to='administration.exam'),
        ),
    ]
