# Generated by Django 5.2.11 on 2026-03-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_growth_theme'),
    ]

    operations = [
        # Must remove the UniqueConstraint(level, unit_number) BEFORE dropping the level field.
        # SQLite recreates the whole table when dropping a column, and the constraint
        # references 'level' — which no longer exists in the rebuilt schema.
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_per_level',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='vocabularyitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='vocabularyitem',
            name='exam',
        ),
        migrations.DeleteModel(
            name='GrammarContent',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='VocabularyItem',
        ),
    ]
