# Generated by Django 5.2.11 on 2026-03-08 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_unit_level_remove_vocabularyitem_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persistent_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
