# Generated by Django 5.2.11 on 2026-05-30 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userstreak_userxp_quizscore'),
        ('course', '0015_alter_grammarlearnitem_exam_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReviseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('vocab', 'Vocabulary'), ('grammar', 'Grammar')], max_length=10)),
                ('wrong_count', models.PositiveIntegerField(default=1)),
                ('next_review_date', models.DateField()),
                ('review_interval', models.PositiveIntegerField(default=4)),
                ('last_answered_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.grammarlearnitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_revise_questions', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.vocabularyitem')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review_date', 'is_active'], name='core_dailyr_user_id_9a5271_idx')],
            },
        ),
    ]
