"""Initial migration for the course app.

Notes:
- The `UserVocabState` table is created in `0001_uservocabstate` using raw SQL.
    We keep the model in migration *state* here (so Django knows it exists), but
    do not try to create the table again (avoids SQLite 'table already exists').
- The other models map to `core_*` tables and are `managed=False`.
"""

# Generated by Django 5.2.11 on 2026-03-03 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_uservocabstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar', to='course.unit')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_items', to='administration.exam')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Grammar explanation, sentence patterns, particle usage')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_grammarcontent',
                'ordering': ['order', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_level',
                'ordering': ['order', 'level_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='course.level')),
                ('unit_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_unit',
                'ordering': ['order', 'unit_number'],
                'managed': False,
                'constraints': [models.UniqueConstraint(fields=('level', 'unit_number'), name='unique_unit_per_level')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='course.unit')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='administration.exam')),
                ('target', models.CharField(help_text='Target word (Hiragana)', max_length=255)),
                ('correct', models.CharField(help_text='Correct English translation', max_length=255)),
                ('wrong1', models.CharField(help_text='Wrong option 1', max_length=255)),
                ('wrong2', models.CharField(help_text='Wrong option 2', max_length=255)),
                ('wrong3', models.CharField(help_text='Wrong option 3', max_length=255)),
                ('correct_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Auto-calculated: which slot (A-D) contains the correct answer after shuffle', max_length=1)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_vocabularyitem',
                'ordering': ['order', 'id'],
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='UserVocabState',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('streak_correct', models.PositiveIntegerField(default=0)),
                        ('streak_normal', models.PositiveIntegerField(default=0)),
                        ('lapses', models.PositiveIntegerField(default=0)),
                        ('is_weak', models.BooleanField(default=False)),
                        ('mode', models.CharField(choices=[('normal', 'Normal (Hiragana → English)'), ('flip', 'Flip (English → Hiragana)'), ('speed', 'Speed Drill')], default='normal', max_length=10)),
                        ('mastered', models.BooleanField(default=False)),
                        ('last_answered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                        ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                        ('half_life_days', models.FloatField(default=1.0)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_states', to=settings.AUTH_USER_MODEL)),
                        ('vocab_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='course.vocabularyitem')),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('user', 'vocab_item'), name='unique_user_vocab_state')],
                        'indexes': [
                            models.Index(fields=['user', 'mastered']),
                            models.Index(fields=['user', 'due_at']),
                            models.Index(fields=['user', 'is_weak']),
                        ],
                    },
                ),
            ],
        ),
    ]
