# Generated by GitHub Copilot on 2026-03-04

from django.db import migrations


CREATE_SQL = """
-- Restore course tables that are mapped (managed=False) to core_* names.

CREATE TABLE IF NOT EXISTS core_level (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    level_number INTEGER NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT 1,
    "order" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS core_unit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    level_id INTEGER NOT NULL REFERENCES core_level(id) ON DELETE CASCADE,
    unit_number INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT 1,
    "order" INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_unit_per_level
    ON core_unit(level_id, unit_number);

CREATE INDEX IF NOT EXISTS core_unit_level_id_idx ON core_unit(level_id);

CREATE TABLE IF NOT EXISTS core_vocabularyitem (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    unit_id INTEGER NOT NULL REFERENCES core_unit(id) ON DELETE CASCADE,
    exam_id INTEGER NULL REFERENCES administration_exam(id) ON DELETE CASCADE,
    target VARCHAR(255) NOT NULL,
    correct VARCHAR(255) NOT NULL,
    wrong1 VARCHAR(255) NOT NULL,
    wrong2 VARCHAR(255) NOT NULL,
    wrong3 VARCHAR(255) NOT NULL,
    correct_answer VARCHAR(1) NOT NULL DEFAULT '',
    "order" INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS core_vocabularyitem_unit_id_idx ON core_vocabularyitem(unit_id);
CREATE INDEX IF NOT EXISTS core_vocabularyitem_exam_id_idx ON core_vocabularyitem(exam_id);

CREATE TABLE IF NOT EXISTS core_grammarcontent (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    unit_id INTEGER NOT NULL REFERENCES core_unit(id) ON DELETE CASCADE,
    exam_id INTEGER NULL REFERENCES administration_exam(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL DEFAULT '',
    content TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS core_grammarcontent_unit_id_idx ON core_grammarcontent(unit_id);
CREATE INDEX IF NOT EXISTS core_grammarcontent_exam_id_idx ON core_grammarcontent(exam_id);
"""

REVERSE_SQL = """
DROP TABLE IF EXISTS core_grammarcontent;
DROP TABLE IF EXISTS core_vocabularyitem;
DROP TABLE IF EXISTS core_unit;
DROP TABLE IF EXISTS core_level;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_exam'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(CREATE_SQL, reverse_sql=REVERSE_SQL),
    ]
