"""Normalize legacy UserVocabState index names.

Historically this project created SQLite indexes with inconsistent names
(sometimes table-prefixed, sometimes not). Django's built-in RenameIndex can be
fragile on SQLite and may attempt to DROP an index name that doesn't exist.

This migration:
- Updates the *database* safely via explicit CREATE INDEX / DROP INDEX.
- Updates the *migration state* to the new names so Django doesn't keep
  generating new rename migrations.
"""

# Generated by Django 5.2.11 on 2026-03-04 04:21

from django.db import migrations


def _safe_fix_indexes(apps, schema_editor):
    UserVocabState = apps.get_model('course', 'UserVocabState')
    tbl = UserVocabState._meta.db_table
    qn = schema_editor.quote_name

    cursor = schema_editor.connection.cursor()
    cursor.execute(f"PRAGMA index_list('{tbl}')")
    existing = {row[1] for row in cursor.fetchall()}

    specs = [
        (
            'course_user_user_id_9a6e8b_idx',
            ['user_id', 'mastered'],
            {
                'uservocabstate_user_mastered_idx',
                f'{tbl}_user_mastered_idx',
            },
        ),
        (
            'course_user_user_id_b845f9_idx',
            ['user_id', 'due_at'],
            {
                'uservocabstate_user_due_at_idx',
                'uservocabstate_user_due_idx',
                f'{tbl}_user_due_at_idx',
                f'{tbl}_user_due_idx',
            },
        ),
        (
            'course_user_user_id_5a05e3_idx',
            ['user_id', 'is_weak'],
            {
                'uservocabstate_user_weak_idx',
                f'{tbl}_user_weak_idx',
            },
        ),
    ]

    for new_name, cols, old_candidates in specs:
        # create new index if missing
        if new_name not in existing:
            cols_sql = ', '.join(qn(c) for c in cols)
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS {qn(new_name)} ON {qn(tbl)} ({cols_sql})'
            )
            existing.add(new_name)

        # drop any legacy names that might exist
        for old_name in old_candidates:
            if old_name in existing and old_name != new_name:
                cursor.execute(f'DROP INDEX IF EXISTS {qn(old_name)}')
                existing.discard(old_name)


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_restore_core_course_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_safe_fix_indexes, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='uservocabstate',
                    new_name='course_user_user_id_9a6e8b_idx',
                    old_name='uservocabstate_user_mastered_idx',
                ),
                migrations.RenameIndex(
                    model_name='uservocabstate',
                    new_name='course_user_user_id_b845f9_idx',
                    old_name='uservocabstate_user_due_at_idx',
                ),
                migrations.RenameIndex(
                    model_name='uservocabstate',
                    new_name='course_user_user_id_5a05e3_idx',
                    old_name='uservocabstate_user_weak_idx',
                ),
            ],
        ),
    ]
