# Generated by Django 5.2.11 on 2026-03-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_restore_core_course_tables'),
    ]


# SQLite (and other backends) can raise if the index we're trying to rename
# doesn't exist.  Over the lifespan of the project the index names have been
# generated inconsistently (sometimes prefixed with the table name, sometimes
# not), so rather than rely on Django's RenameIndex helper directly we perform
# the operation in Python and only execute it when the source name is
# actually present.

def _safe_rename_indexes(apps, schema_editor):
    """Create the new index names and drop any old variants by hand.

    SQLite's built‑in ``schema_editor.rename_index`` is fragile: it still
    tries to DROP the unprefixed name after doing the rename, which is
    exactly the error you observed.  Rather than battle those internal
    details we simply execute explicit ``CREATE INDEX``/``DROP INDEX`` SQL
    when the source index exists.
    """

    UserVocabState = apps.get_model('course', 'UserVocabState')
    tbl = UserVocabState._meta.db_table

    cursor = schema_editor.connection.cursor()
    cursor.execute(f"PRAGMA index_list('{tbl}')")
    existing = {row[1] for row in cursor.fetchall()}

    pairs = [
        ('uservocabstate_user_mastered_idx', 'course_user_user_id_9a6e8b_idx'),
        ('uservocabstate_user_due_at_idx', 'course_user_user_id_b845f9_idx'),
        ('uservocabstate_user_weak_idx', 'course_user_user_id_5a05e3_idx'),
    ]

    for old, new in pairs:
        # determine all possible names the legacy index might have had
        candidates = [old]
        if not old.startswith(tbl + "_"):
            suffix = old
            if suffix.startswith("uservocabstate_"):
                suffix = suffix[len("uservocabstate_") :]
            candidates.append(f"{tbl}_{suffix}")

        found = None
        for cname in candidates:
            if cname in existing:
                found = cname
                break
        if not found:
            continue

        # create the new index if necessary, then drop the old one
        # we know exactly which columns go with each new index name, so build
        # the appropriate SQL directly.
        if 'mastered' in new:
            sql_create = f"CREATE INDEX IF NOT EXISTS {new} ON {tbl} (user_id, mastered)"
        elif 'due' in new:
            sql_create = f"CREATE INDEX IF NOT EXISTS {new} ON {tbl} (user_id, due_at)"
        else:  # weak index
            sql_create = f"CREATE INDEX IF NOT EXISTS {new} ON {tbl} (user_id, is_weak)"
        cursor.execute(sql_create)
        cursor.execute(f"DROP INDEX IF EXISTS {found}")


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_restore_core_course_tables'),
    ]

    operations = [
        migrations.RunPython(_safe_rename_indexes, reverse_code=migrations.RunPython.noop),
    ]
