# Generated by Django 5.2.11 on 2026-03-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_restore_core_course_tables'),
    ]


# SQLite (and other backends) can raise if the index we're trying to rename
# doesn't exist.  Over the lifespan of the project the index names have been
# generated inconsistently (sometimes prefixed with the table name, sometimes
# not), so rather than rely on Django's RenameIndex helper directly we perform
# the operation in Python and only execute it when the source name is
# actually present.

def _safe_rename_indexes(apps, schema_editor):
    UserVocabState = apps.get_model('course', 'UserVocabState')
    tbl = UserVocabState._meta.db_table

    cursor = schema_editor.connection.cursor()
    cursor.execute(f"PRAGMA index_list('{tbl}')")
    existing = {row[1] for row in cursor.fetchall()}

    # list of (possible-old-name, new-name)
    pairs = [
        ('uservocabstate_user_mastered_idx', 'course_user_user_id_9a6e8b_idx'),
        ('uservocabstate_user_due_at_idx', 'course_user_user_id_b845f9_idx'),
        ('uservocabstate_user_weak_idx', 'course_user_user_id_5a05e3_idx'),
    ]

    for old, new in pairs:
        # some indexes were created with the table name prefixed, others were
        # not.  The `old` variable usually starts with "uservocabstate_"; if
        # we simply prepend the table name again we would end up with
        # "course_uservocabstate_uservocabstate_…".  Generate the two
        # reasonable candidates and test both.
        candidates = [old]
        if not old.startswith(tbl + "_"):
            suffix = old
            if suffix.startswith("uservocabstate_"):
                suffix = suffix[len("uservocabstate_") :]
            candidates.append(f"{tbl}_{suffix}")
        for cname in candidates:
            if cname in existing:
                try:
                    schema_editor.rename_index(UserVocabState, cname, new)
                except Exception:
                    # ignore any error (index might be absent on another
                    # backend) and move on
                    pass
                break


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_restore_core_course_tables'),
    ]

    operations = [
        migrations.RunPython(_safe_rename_indexes, reverse_code=migrations.RunPython.noop),
    ]
