# Generated by Django 5.0.7 on 2024-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_grammarlearnitem_main_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammarlearnitem',
            old_name='example_en',
            new_name='example_en_1',
        ),
        migrations.RenameField(
            model_name='grammarlearnitem',
            old_name='example_jp',
            new_name='example_jp_1',
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_en_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_en_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_en_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_en_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_jp_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_jp_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_jp_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarlearnitem',
            name='example_jp_5',
            field=models.TextField(blank=True),
        ),
    ]
