# Generated by Django 5.2.11 on 2026-03-09 18:25
# Manually written migration: SQLite created exam_code with UNIQUE, but the
# model never intended that.  Recreate the table without that constraint.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_simplify_example_fields'),
    ]

    operations = [
        migrations.RunSQL(
            # SQLite doesn't support DROP CONSTRAINT, so we recreate the table
            sql="""
                -- 1. rename old table
                ALTER TABLE "core_grammarpakkaitem" RENAME TO "_gpi_old";

                -- 2. recreate without UNIQUE on exam_code
                CREATE TABLE "core_grammarpakkaitem" (
                    "id"               integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    "step_type"        smallint unsigned NOT NULL CHECK ("step_type" >= 0),
                    "logic_formula"    varchar(255) NOT NULL,
                    "english_prompt"   varchar(255) NOT NULL,
                    "correct_sentence" text NOT NULL,
                    "word_blocks"      text NOT NULL,
                    "particle_target"  varchar(32) NOT NULL,
                    "explanation_hint" text NOT NULL,
                    "order"            integer unsigned NOT NULL CHECK ("order" >= 0),
                    "exam_id"          bigint NULL REFERENCES "administration_exam" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "unit_id"          bigint NOT NULL REFERENCES "core_unit" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "exam_level"       smallint unsigned NOT NULL CHECK ("exam_level" >= 0),
                    "distractors"      text NOT NULL,
                    "exam_code"        varchar(32) NULL,
                    CONSTRAINT "unique_grammarpakka_unit_step_prompt"
                        UNIQUE ("unit_id", "step_type", "english_prompt")
                );

                -- 3. copy data
                INSERT INTO "core_grammarpakkaitem"
                SELECT * FROM "_gpi_old";

                -- 4. drop old table
                DROP TABLE "_gpi_old";

                -- 5. restore indexes
                CREATE INDEX "core_grammarpakkaitem_exam_id_df1b020b"
                    ON "core_grammarpakkaitem" ("exam_id");
                CREATE INDEX "core_grammarpakkaitem_unit_id_df98cac1"
                    ON "core_grammarpakkaitem" ("unit_id");
                CREATE INDEX "gpi_unit_step_order_idx"
                    ON "core_grammarpakkaitem" ("unit_id", "step_type", "order");
                CREATE INDEX "gpi_exam_meta_idx"
                    ON "core_grammarpakkaitem" ("exam_level", "exam_code");
            """,
            # reverse: add the unique back (unlikely to be needed)
            reverse_sql="""
                ALTER TABLE "core_grammarpakkaitem" RENAME TO "_gpi_old";
                CREATE TABLE "core_grammarpakkaitem" (
                    "id"               integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    "step_type"        smallint unsigned NOT NULL CHECK ("step_type" >= 0),
                    "logic_formula"    varchar(255) NOT NULL,
                    "english_prompt"   varchar(255) NOT NULL,
                    "correct_sentence" text NOT NULL,
                    "word_blocks"      text NOT NULL,
                    "particle_target"  varchar(32) NOT NULL,
                    "explanation_hint" text NOT NULL,
                    "order"            integer unsigned NOT NULL CHECK ("order" >= 0),
                    "exam_id"          bigint NULL REFERENCES "administration_exam" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "unit_id"          bigint NOT NULL REFERENCES "core_unit" ("id") DEFERRABLE INITIALLY DEFERRED,
                    "exam_level"       smallint unsigned NOT NULL CHECK ("exam_level" >= 0),
                    "distractors"      text NOT NULL,
                    "exam_code"        varchar(32) NULL UNIQUE,
                    CONSTRAINT "unique_grammarpakka_unit_step_prompt"
                        UNIQUE ("unit_id", "step_type", "english_prompt")
                );
                INSERT INTO "core_grammarpakkaitem" SELECT * FROM "_gpi_old";
                DROP TABLE "_gpi_old";
            """,
        ),
    ]
