# Generated by Django 5.2.11 on 2026-05-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_drop_exam_code_unique_on_pakka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarlearnitem',
            name='exam_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='grammarlearnitem',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grammarlearnitem',
            name='logic_formula',
            field=models.CharField(max_length=255),
        ),
    ]
