# Generated by Django 5.2.11 on 2026-05-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_grammarlearnitem_exam_code_and_more'),
        ('course', '0015_alter_grammarlearnitem_exam_code_and_more'),
    ]

    operations = [
    ]
