"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f+if26+p_4zkh#zct)7k95#h^3@$nrih5nzb1vblv@0b=5a7w_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# Allow the Cloudflare tunnel hostname and the zynix.us zone
ALLOWED_HOSTS += [
    "jback.zynix.us",
    ".zynix.us",
]

# React dev server origins for CSRF checks (unsafe methods need trusted origins)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    # Capacitor / Android WebView origin (Capacitor serves the app from localhost)
    "http://localhost",
    "http://127.0.0.1",
    # Some Capacitor/Ionic builds use a custom scheme origin
    "capacitor://localhost",
    "ionic://localhost",
    # Public hostname
    "https://jback.zynix.us",
]

# Allow the Capacitor app to call the API using cookies (credentials).
# Capacitor typically sets Origin: http://localhost (sometimes with a port).
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(?::\\d+)?$",
    r"^http://127\\.0\\.0\\.1(?::\\d+)?$",
    r"^capacitor://localhost$",
    r"^ionic://localhost$",
]

# Cross-site cookies are required for session-based auth from a Capacitor origin
# (the app runs at http://localhost inside the WebView, calling https://jback.zynix.us).
# In production (DEBUG=False) we default to SameSite=None; Secure.
# In development, keep Django defaults so cookies still work over plain HTTP.
if (not DEBUG) or (os.environ.get("DJANGO_SECURE_COOKIES") == "1"):
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True

# When running behind Cloudflare (or other reverse proxies) trust the
# X-Forwarded-Proto header so Django knows the original request scheme.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'administration.apps.AdministrationConfig',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

# Optionally enable WhiteNoise if installed (avoids startup errors when missing)
try:
    import importlib

    if importlib.util.find_spec('whitenoise') is not None:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
except Exception:
    # If whitenoise isn't installed, skip adding it to middleware.
    pass

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Use WhiteNoise to serve static files with compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'core.User'

# Optional: used for certificate PDFs
SENSEI_SIGNATURE_PATH = BASE_DIR / 'assets' / 'sensei-signature.png'

# Billing (optional, for Stripe Checkout stub)
STRIPE_SECRET_KEY = ""
STRIPE_SUCCESS_URL = "http://localhost:5173/app/shop?success=1"
STRIPE_CANCEL_URL = "http://localhost:5173/app/shop?canceled=1"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
