"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file (if present) — keeps secrets out of source code
# override=True ensures .env always wins over stale system env vars
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f+if26+p_4zkh#zct)7k95#h^3@$nrih5nzb1vblv@0b=5a7w_'

# SECURITY WARNING: don't run with debug turned on in production!
# Default stays True for local development, but production should set `DJANGO_DEBUG=0`.
_debug_env = os.environ.get("DJANGO_DEBUG", "1").strip().lower()
DEBUG = _debug_env in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

# Allow the Cloudflare tunnel hostname and the zynix.us zone
ALLOWED_HOSTS += [
    "jback.zynix.us",
    ".zynix.us",
]

# React dev server origins for CSRF checks (unsafe methods need trusted origins)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    # Capacitor / Android WebView origin (Capacitor serves the app from localhost)
    "http://localhost",
    "http://127.0.0.1",
    # Android WebView often uses https://localhost as the app origin
    "https://localhost",
    "https://127.0.0.1",
    # Some Capacitor/Ionic builds use a custom scheme origin
    "capacitor://localhost",
    "ionic://localhost",
    # Public hostname
    "https://jback.zynix.us",
]

# Allow the Capacitor app to call the API using cookies (credentials).
# Capacitor typically sets Origin: http://localhost (sometimes with a port).
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(?::\\d+)?$",
    r"^http://127\\.0\\.0\\.1(?::\\d+)?$",
    r"^https://localhost(?::\\d+)?$",
    r"^https://127\\.0\\.0\\.1(?::\\d+)?$",
    r"^capacitor://localhost$",
    r"^ionic://localhost$",
]

# Cross-site cookies are required for session-based auth from a Capacitor origin
# (the app runs at http://localhost inside the WebView, calling https://jback.zynix.us).
# In production (DEBUG=False) we default to SameSite=None; Secure.
# In development, keep Django defaults so cookies still work over plain HTTP.
if (not DEBUG) or (os.environ.get("DJANGO_SECURE_COOKIES") == "1"):
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True

# When running behind Cloudflare (or other reverse proxies) trust the
# X-Forwarded-Proto header so Django knows the original request scheme.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'administration.apps.AdministrationConfig',
    'core.apps.CoreConfig',
    'course.apps.CourseConfig',
    'payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.token_auth_middleware.PersistentTokenAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

# Optionally enable WhiteNoise if installed (avoids startup errors when missing)
try:
    import importlib

    if importlib.util.find_spec('whitenoise') is not None:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
except Exception:
    # If whitenoise isn't installed, skip adding it to middleware.
    pass

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Use WhiteNoise to serve static files with compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'core.User'

# Keep users logged in until they explicitly logout.
# - Persist session cookie across browser restarts
# - Refresh expiry on every request (sliding session)
# NOTE: Choose a long age; logout will still invalidate the session immediately.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365 * 5  # 5 years

# Optional: used for certificate PDFs
SENSEI_SIGNATURE_PATH = BASE_DIR / 'assets' / 'sensei-signature.png'

# ── Cashfree Payment Gateway ──────────────────────────────────────────────────
# Sign up at https://merchant.cashfree.com → Settings → API Keys
# For testing use ENV=TEST; switch to PRODUCTION when live
CASHFREE_APP_ID      = os.environ.get("CASHFREE_APP_ID", "")
CASHFREE_SECRET_KEY  = os.environ.get("CASHFREE_SECRET_KEY", "")
CASHFREE_WEBHOOK_SECRET = os.environ.get("CASHFREE_WEBHOOK_SECRET", "")
CASHFREE_ENV         = os.environ.get("CASHFREE_ENV", "TEST")   # "TEST" or "PRODUCTION"
# Frontend URLs Cashfree redirects to after payment
CASHFREE_RETURN_URL  = os.environ.get("CASHFREE_RETURN_URL", "http://localhost:5173/app/shop?result=1")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Apps Script endpoint used to send OTP emails. Set via environment in production.
APPS_SCRIPT_URL = os.environ.get('APPS_SCRIPT_URL', 'https://script.google.com/macros/s/AKfycby0z8cq7XWKBM7BuoXRV9lBBA8YS2wFNFOlZ8YYCeZifjloaiIvXE-45vfKiEDLZ4Wd/exec')
# Shared secret to include when calling the Apps Script (required for security).
APPS_SCRIPT_SECRET = os.environ.get('APPS_SCRIPT_SECRET', 'bengo-otp-secret-2026-secure-key-xyz789')
