# Generated by Django 5.2.11 on 2026-05-30 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0015_alter_grammarlearnitem_exam_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_hint_usage_per_day')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField(help_text="User's personal memory hint or mnemonic")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_hints', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='course.vocabularyitem')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'vocabulary_item'], name='hints_vocab_user_id_3a7521_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'vocabulary_item'), name='unique_vocab_hint_per_user')],
            },
        ),
    ]
